import os
import json

from dotenv import load_dotenv
from google import genai
from google.genai import types


load_dotenv()

GEMINI_API_KEY = os.getenv("GEMINI_API_KEY")

if not GEMINI_API_KEY:
    raise ValueError(
        "GEMINI_API_KEY is not set. "
        "Add your Gemini API key to the .env file."
    )

client = genai.Client(api_key=GEMINI_API_KEY)


def generate_insights(verified_results):

    prompt = f"""
You are the Insight Agent in a Multi-Agent Data Analysis System.

Your job is to interpret VERIFIED statistical results generated by
Python-based analysis agents.

IMPORTANT RULES:

1. Use ONLY the provided verified results.
2. Never invent numbers.
3. Never modify statistical values.
4. Do not create statistics that are not provided.
5. Do not claim causation from correlation.
6. Clearly mention when evidence is insufficient.
7. Identify meaningful patterns and relationships.
8. Explain findings in simple business language.
9. Every numerical statement must be supported by the provided results.
10. Give practical recommendations based only on the evidence.

The Python agents have already performed the statistical analysis.
You are the interpretation and reasoning layer.

VERIFIED RESULTS:

{json.dumps(verified_results, indent=2, default=str)}
"""

    response = client.models.generate_content(
        model="gemini-3.8-flash",
        contents=prompt,
        config=types.GenerateContentConfig(
            response_mime_type="application/json",
            response_schema={
                "type": "OBJECT",
                "properties": {
                    "summary": {
                        "type": "STRING"
                    },
                    "key_insights": {
                        "type": "ARRAY",
                        "items": {
                            "type": "OBJECT",
                            "properties": {
                                "title": {
                                    "type": "STRING"
                                },
                                "insight": {
                                    "type": "STRING"
                                },
                                "evidence": {
                                    "type": "STRING"
                                },
                                "interpretation": {
                                    "type": "STRING"
                                }
                            },
                            "required": [
                                "title",
                                "insight",
                                "evidence",
                                "interpretation"
                            ]
                        }
                    },
                    "recommendations": {
                        "type": "ARRAY",
                        "items": {
                            "type": "STRING"
                        }
                    },
                    "risk_factors": {
                        "type": "ARRAY",
                        "items": {
                            "type": "STRING"
                        }
                    }
                },
                "required": [
                    "summary",
                    "key_insights",
                    "recommendations",
                    "risk_factors"
                ]
            }
        )
    )

    response_text = response.text.strip()

    return json.loads(response_text)

